roslaunch gazelle_sim_barrel_course barrel_course.launch
roslaunch gazelle_sim_color_line_follow color_line_folllow.launch
roslaunch gazelle_sim_color_zones color_zones.launch
roslaunch gazelle_sim_crosswalk crosswalk.launch
roslaunch gazelle_sim_igvc igvc.launch
roslaunch gazelle_sim_line_course line_course.launch
roslaunch gazelle_sim_line_course_obs line_course_obs.launch
roslaunch gazelle_sim_ltu_igvc ltu_igvc.launch
roslaunch gazelle_sim_maze maze.launch
roslaunch gazelle_sim_obstructions obstructions.launch
roslaunch gazelle_sim_waypoint_course waypoint_course.launch


